# Generated by Django 2.1.7 on 2019-10-07 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191002_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 8, 37, 39, 442791, tzinfo=utc)),
        ),
    ]
