name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  IMAGE_NAME: mysite:1.0
  
jobs:
  image_build:
    strategy:
      matrix:
        servers: [test_ci]   # 选择label为test_ci的runner
    runs-on: ${{matrix.servers}}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "$IMAGE_NAME"
        docker build --file Dockerfile --tag "$IMAGE_NAME" .
    - name: Cleanup
      run: rm -rf ${{github.event.repository.name}}
  
  deploy_redis:
    # needs: image_build
    strategy:
      matrix:
        servers: [test_ci]   # 选择label为test_ci的runner
    runs-on: ${{matrix.servers}}
    steps:
    - name: Run the nginx
      run: if [[ -z `docker ps | grep redis| grep '6379->6379'` ]]; then docker run -d --name redis -p 6379:6379 redis; else echo "exist"; fi
      
  deploy_mysite:
    needs: [image_build, deploy_redis]
    strategy:
      matrix:
        servers: [test_ci]   # 选择label为test_ci的runner
    runs-on: ${{matrix.servers}}
    steps:
    - name: Run the Docker image
      run: |
        if [[ -n `docker ps | grep mysite| grep '8000->8000'` ]]; then docker stop mysite; docker rm mysite;fi
        docker run -d --name mysite -p 8000:8000 "$IMAGE_NAME"
