name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deployment:
    strategy:
      matrix:
        servers: [test_ci]   # 选择label为test_ci的runner
    runs-on: ${{matrix.servers}}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mysite:$(date +%s)
